---
title: "Data 612 Project 2"
author: "Stephen Haslett"
date: "6/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(recommenderlab)
library(ggplot2)

set.seed(1)
data(MovieLense)
```

```{r, warning=FALSE, message=FALSE}
# User similarity.
similarity_users <- similarity(MovieLense[1:4, ], method = 'cosine', which = 'users')
similarity_users <- as.matrix(similarity_users)
similarity_users
image(similarity_users, main = 'User similarity')
```


```{r, warning=FALSE, message=FALSE}
# Item similarity.
similarity_items <- similarity(MovieLense[, 1:4], method = 'cosine', which = 'items')
similarity_items <- as.matrix(similarity_items)
similarity_items
image(similarity_items, main = 'Item similarity')
```



### Explore the data
```{r, warning=FALSE, message=FALSE}
ratings_vector <- as.vector(MovieLense@data)
# Remove empty values.
ratings_vector <- ratings_vector[ratings_vector != 0]
ratings_table <- table(ratings_vector)
ratings_table


```


```{r, warning=FALSE, message=FALSE}
ratings_vector <- factor(ratings_vector)
qplot(ratings_vector) + ggtitle('Distribution of Ratings')
```


### Views per movie.
```{r, warning=FALSE, message=FALSE}
views_per_movie <- colCounts(MovieLense)
views_table <- data.frame(
  movie = names(views_per_movie),
  views = views_per_movie
)

views_table <- views_table[order(views_table$views, decreasing = TRUE), ]
ggplot(views_table[1:6, ], aes(x = movie, y = views)) +
geom_bar(stat="identity") +
theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ggtitle("Number of views of the top movies")

```


## Data Preperation
```{r, warning=FALSE, message=FALSE}
# Select only users who have rated at least 50 movies, and
# movies that have been watched at least 100 times.
movie_ratings <- MovieLense[rowCounts(MovieLense) > 50, colCounts(MovieLense) > 100]
movie_ratings
average_ratings_per_user <- rowMeans(movie_ratings)
average_ratings_per_user
```


#### Normalize the data
```{r, warning=FALSE, message=FALSE}
normalized_movie_ratings <- normalize(movie_ratings)
```


#### Create the training and test data
```{r, warning=FALSE, message=FALSE}
train <- sample(x = c(TRUE, FALSE), size = nrow(movie_ratings), replace =TRUE, prob = c(0.8, 0.2))
training_data <- movie_ratings[train, ]
test_data <- movie_ratings[!train, ]
```


## Item Based Collaborative Filtering

#### Build the item based model
```{r, warning=FALSE, message=FALSE}
item_item_model <- Recommender(data = training_data, method = 'IBCF')
item_item_model
```


### Apply the model to the test data.
```{r, warning=FALSE, message=FALSE}
predicted <- predict(object = item_item_model, newdata = test_data, n = 6)
recommendation_matrix <- sapply(predicted@items, function(x) {
                           colnames(movie_ratings)[x]
                         })

# First 4 user recommendations.
recommendation_matrix[, 1:4]
```


### Most popular movies
```{r, warning=FALSE, message=FALSE}
items_count <- factor(table(recommendation_matrix))
qplot(items_count) + ggtitle('Distribution of IBCF items')
```

```{r, warning=FALSE, message=FALSE}
items_count_sorted <- sort(items_count, decreasing = TRUE)
top_items <- head(items_count_sorted, n = 10)
top_items_table <- data.frame(top_items)
top_items_table
```


## User Based Collaborative Filtering

#### Build the user based model
```{r, warning=FALSE, message=FALSE}
user_user_model <- Recommender(data = training_data, method = 'UBCF')
user_user_model
```

### Apply the model to the test data.
```{r, warning=FALSE, message=FALSE}
predicted <- predict(object = user_user_model, newdata = test_data, n = 6)
recommendation_matrix <- sapply(predicted@items, function(x) {
                           colnames(movie_ratings)[x]
                         })

# First 4 user recommendations.
recommendation_matrix[, 1:4]
```

### Most popular movies
```{r, warning=FALSE, message=FALSE}
items_count <- factor(table(recommendation_matrix))
qplot(items_count) + ggtitle('Distribution of UBCF items')
```

```{r, warning=FALSE, message=FALSE}
items_count_sorted <- sort(items_count, decreasing = TRUE)
top_items <- head(items_count_sorted, n = 10)
top_items_table <- data.frame(top_items)
top_items_table
```
