---
title: "Data 612 Project 1 Global Baseline Predictors and RMSE"
author: "Stephen Haslett"
date: "6/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
```


#### Load the ratings data into a dataframe.
```{r, warning=FALSE, message=FALSE}
csv_file <- 'https://raw.githubusercontent.com/stephen-haslett/data612/612-project-1/movie_ratings.csv'
movie_ratings_data <- read.csv(csv_file, header = TRUE, sep = ',', stringsAsFactors = FALSE)
colnames(movie_ratings_data) <- gsub('.', ' ', colnames(movie_ratings_data), fixed = TRUE)
movie_ratings_data %>% kable(caption = 'Movie Ratings') %>% kable_styling('striped', full_width = TRUE)
```


### Create a user-item matrix.
```{r, warning=FALSE, message=FALSE}
rownames(movie_ratings_data) <- movie_ratings_data$Viewers
ratings <- select(movie_ratings_data, 2:7)
user_item_matrix <- data.matrix(ratings)
user_item_matrix %>% kable(caption = 'Movie Ratings') %>% kable_styling('striped', full_width = TRUE)
```




#### Break your ratings into separate training and test datasets.
```{r, warning=FALSE, message=FALSE}
sample <- sample.int(n = nrow(user_item_matrix), size = floor(0.7 * nrow(user_item_matrix)), replace = FALSE)
train_data <- user_item_matrix[sample, ]
test_data  <- user_item_matrix[-sample, ]

train_data %>% kable(caption = 'Training Data') %>% kable_styling('striped', full_width = TRUE)
test_data %>% kable(caption = 'Test Data') %>% kable_styling('striped', full_width = TRUE)
```





